name: pose_mammanet
freeze_backbone: false
backbone:
  type: ViT
  img_size: ${image_size}
  patch_size: 16
  embed_dim: 768
  depth: 12
  num_heads: 12
  ratio: 1
  use_checkpoint: false
  mlp_ratio: 4
  qkv_bias: true
  drop_path_rate: 0.3
use_mask: ${use_mask_encoder}
decoder:
  layer_name: MammaNetDecoder
  d_model: 768
  n_heads: 8
  n_layers: 6
  n_landmarks: ${num_joints}
  transformer_dim_feedforward: 2048
  ldmks_dim: 2
  dropout: 0.1
  uncertainty: true
  visibility: true
  contact: true
  floor_contact: true